#!/usr/bin/env python3
"""Check that file types are detected correctly.

Only uses the standard library. Includes tests of test code inline.
"""
# tests/automated/file-type-detection/run
# Copyright 2021 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
import json
from pathlib import Path
from subprocess import check_call


TESTS = Path(__file__).parent
DATA = TESTS / "fixtures"
OUTPUT = TESTS / "run.txt"


def _issues() -> int:
    result = 0
    for path in DATA.rglob("*"):

        if not path.is_file():
            continue

        command = (
            "vim",
            f"+redir! > {OUTPUT}",
            "+set filetype?",
            "+quit",
            path,
        )
        if check_call(command) != 0:
            print(f"Error running {command}")

        with path.open() as file:
            expected = _clean_expected(file.read())
        with OUTPUT.open() as file:
            actual = _clean_actual(file.read())
        if expected != actual:
            print(f"{expected!r} != {actual!r} for {path}")
            result += 1
        else:
            OUTPUT.unlink()
    return result


def _clean_expected(before: str) -> str:
    try:
        after = json.loads(before)["filetype"]
    except json.decoder.JSONDecodeError:
        after = before.strip()
        after = after.removeprefix("# ")
        after = after.removeprefix("// ")
        after = after.removeprefix("-- ")
    return after


def _clean_actual(before: str) -> str:
    after = before.strip()
    return after.removeprefix("filetype=")


def _main() -> int:
    issues = 0
    issues += _clean_actual("\n  filetype=groovy") != "groovy"
    issues += _clean_expected("text\n") != "text"
    issues += _clean_expected("# python") != "python"
    issues += _clean_expected("// javascript") != "javascript"
    issues += _clean_expected('{"filetype":"json"}') != "json"

    return min(_issues(), 1)


if __name__ == "__main__":
    raise SystemExit(_main())
