# pipx.yaml
# Copyright 2021 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
#
- name: Install pipx if pipx --version fails
  hosts: all
  tasks:
    - name: Try running pipx --version
      ansible.builtin.command:
        argv: [pipx, --version]
      failed_when: false
      changed_when: false
      register: pipx_version
    - name: Stop this play if pipx --version succeeded
      ansible.builtin.meta: end_host
      when: pipx_version.rc == 0
    - name: Make sure ~/.local hierarchy exists
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: 0o755
      loop: [~/.local, ~/.local/bin]
    - name: Install pipx to ~/.local/bin
      ansible.builtin.get_url:
        url: https://github.com/pypa/pipx/releases/download/1.2.0/pipx.pyz
        # no checksum published
        dest: ~/.local/bin/pipx
        mode: "0755"
# vim: set filetype=yaml.ansible :
