# site.yaml
# Copyright 2021 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
#
# Run as:
#
#     ansible-playbook -i, site.yaml
#
# This playbook can be run as a normal user, no super-user privileges are
# necessary.
- name: Create the backupdir
  hosts: localhost
  tasks:
    - name: Make sure ~/.backupdir exists
      ansible.builtin.file:
        state: directory
        path: ~/.backupdir
        mode: 0o700

- name: Download scrips to the plugin/ directory
  hosts: localhost
  tasks:
    - name: Create the plugin folder
      file: { state: directory, path: ./plugin/, mode: 0o755 }
    - name: Download osc52.vim
      get_url:
        dest: ./plugin/osc52.vim
        url: https://raw.githubusercontent.com/libapps/libapps-mirror/main/hterm/etc/osc52.vim
    - name: Download fzf.vim, on MacOSX it isn't added to runtimepath, on Alpine
        Linux the fzf-vim package also includes documentation
      get_url:
        dest: ./plugin/fzf.vim
        url: https://raw.githubusercontent.com/junegunn/fzf/master/plugin/fzf.vim
      when: ansible_distribution in ('MacOSX')

- name: Tag vim help files, these tasks always report changes
  hosts: localhost
  tasks:
    - name: Create a temporary file for use as a script to generate help tags
      tempfile: { state: file, suffix: .vim }
      register: site_script
      changed_when: false
    - name: List optional packages
      find: { paths: ~/.vim/pack/submodules/opt/, file_type: directory }
      register: site_find
    - name: Write the commands to the script to avoid an error about too many
        command line flags
      copy:
        dest: "{{ site_script.path }}"
        content: |
          {% for i in  site_find.files %}
          packadd {{ i.path | basename }}
          {% endfor %}
          helptags ALL
          quit
        mode: 0o700
      changed_when: false
    - name: Run the script to generate help tags with vim ( {{ site_script.path }} )
      command: vim -S {{ site_script.path }}
      changed_when: true
    - name: Remove the temporary file used as script for generating help tags
      file:
        path: "{{ site_script.path }}"
        state: absent
      changed_when: false

- name: Make sure packages are available through npx
  hosts: localhost
  tasks:
    - name: npm is available
      ansible.builtin.command: npm --version
      changed_when: no
      register: npm_check
    - name: Stop this play if npm isnt't available
      meta: end_host
      when: npm_check.rc != 0
    - name: Make sure tools are available in the npm cache
      command:
        cmd: npm exec --yes -- {{ item }} --help
        creates: ~/.npm/_npx/*/node_modules/.bin/{{ item }}
      loop:
        - embedme
        - js-yaml
    - name: Make sure markdown-toc is available in the npm cache
      command:
        cmd: npm exec --yes -- markdown-toc --help
        creates: ~/.npm/_npx/*/node_modules/.bin/markdown-toc
      register: npm_exec_markdown_toc_cmd
      failed_when: npm_exec_markdown_toc_cmd.rc not in (0, 1) # 0 if skipped
    - name: Make sure ~/.local/bin exists
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: 0o755
      loop: [~/.local, ~/.local/bin]
    - name: Install ~/.local/bin/prettier
      ansible.builtin.copy:
        dest: ~/.local/bin/prettier
        mode: 0o544
        content: |
          #!/bin/sh
          npm exec --yes -- prettier@2.5.1 "$@"
      when: "'.local/bin' in lookup('env', 'PATH')"
    - name: Add prettier to npm cache
      ansible.builtin.command: prettier --version
      changed_when: no
    - name: Install ~/.local/bin/jsonlint
      ansible.builtin.copy:
        dest: ~/.local/bin/jsonlint
        mode: 0o544
        content: |
          #!/bin/sh
          npm exec --yes -- jsonlint "$@"
      when: "'.local/bin' in lookup('env', 'PATH')"
    - name: Add jsonlint to npm cache
      ansible.builtin.command: jsonlint --version
      changed_when: no
      register: npm_exec_jsonlint_cmd
      failed_when: npm_exec_jsonlint_cmd.rc != 1
    - name: Install ~/.local/bin/lint-all
      ansible.builtin.copy:
        dest: ~/.local/bin/lint-all
        mode: 0o544
        content: |
          #!/bin/sh
          #
          # lint-all
          #
          # Run all of the lint-staged rules on the current repository
          #
          # Dependencies:
          # - npm (tested on version 8.3.0)
          # - git (tested on version 2.25.0)
          #
          # lint-staged is run via npm `exec` (tested on version 12.1.4)
          #
          # See https://www.npmjs.com/package/lint-staged
          #
          # all is a new repository where everything has been staged
          all="$(mktemp -d /tmp/lint-all.XXXXXX)" \
          && cd "$all" \
          && git init -b main \
          && git commit --allow-empty -m "Initial commit" \
          && git -C "$OLDPWD" write-tree \
          | xargs git -C "$OLDPWD" archive \
          | tar x \
          && git add . \
          && npm exec -- lint-staged \
          && cd "$OLDPWD" \
          && rm -rf "$all" \
          && unset all
      when: "'.local/bin' in lookup('env', 'PATH')"

- import_playbook: pipx.yaml
