#!/usr/bin/env ansible-playbook
# site.yaml
# Copyright 2021 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
#
# Run as:
#
#     ansible-playbook -i::1, -c local site.yaml
#
# This playbook can be run as a normal user, no super-user privileges are
# necessary.
- name: Create the backupdir
  hosts: all
  tasks:
    - name: Make sure ~/.backupdir exists
      ansible.builtin.file:
        state: directory
        path: ~/.backupdir
        mode: "0o700"

- name: Download scripts to the plugin/ directory
  hosts: all
  tasks:
    - name: Create the plugin folder
      ansible.builtin.file: { state: directory, path: ./plugin/, mode: "0o755" }
    - name: Download osc52.vim
      ansible.builtin.get_url:
        dest: ./plugin/osc52.vim
        url: |-
          https://raw.githubusercontent.com/libapps/libapps-mirror/main/hterm/etc/osc52.vim
        mode: "0640"
    - name: Download fzf.vim
      ansible.builtin.get_url:
        dest: ./plugin/fzf.vim
        url: |-
          https://raw.githubusercontent.com/junegunn/fzf/master/plugin/fzf.vim
        mode: "0640"
      # On Alpine Linux the fzf-vim package also includes documentation so
      # prefer to install that package manually
      when: ansible_distribution not in ('Alpine')

- name: Make sure packages are available through npx and uv
  hosts: all
  tasks:
    - name: Check if npm is available
      ansible.builtin.command: npm --version
      changed_when: false
      register: npm_check
    - name: Stop this play if npm isn't available
      ansible.builtin.meta: end_host
      when: npm_check.rc != 0
    - name: Make sure tools are available in the npm cache
      ansible.builtin.command:
        cmd: npm exec --yes -- {{ item[0] }} --help
        creates: ~/.npm/_npx/*/node_modules/.bin/{{ item[0] }}
      register: site_npm_exec
      failed_when: site_npm_exec.rc not in item[1]
      # if file in creates: exists the site_npm_exec.rc is 0
      loop:
        - [embedme, [0]]
        - [pyright, [0]]
        - [lint-staged, [0]]
    - name: Make sure markdown-toc is available in the npm cache
      ansible.builtin.command:
        cmd: npm exec --yes -- markdown-toc --help
        creates: ~/.npm/_npx/*/node_modules/.bin/markdown-toc
      register: npm_exec_markdown_toc_cmd
      failed_when: npm_exec_markdown_toc_cmd.rc not in (0, 1) # 0 if skipped
    - name: Make sure ~/.local/bin exists
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: "0o755"
      loop: [~/.local, ~/.local/bin]
    - name: Add prettier to npm cache
      ansible.builtin.command: npm exec --yes -- prettier --version
      when: "'.local/bin' in lookup('env', 'PATH')"
      changed_when: false
    - name: Add jsonlint to npm cache
      ansible.builtin.command: npm exec --yes -- jsonlint --version
      when: "'.local/bin' in lookup('env', 'PATH')"
      changed_when: false
      register: npm_exec_jsonlint_cmd
      failed_when: npm_exec_jsonlint_cmd.rc != 1
    - name: Try running uv self version
      ansible.builtin.command: uv self version
      changed_when: false
      register: uv_check
    - name: Stop this play if uv isn't available
      ansible.builtin.meta: end_host
      when: uv_check.rc != 0
    - name: Add to the uv cache so that features and tests can run offline
      ansible.builtin.command: "uv tool run {{ item }}"
      changed_when: true
      loop:
        - reuse --version
        - usort --version
        - ruff --version
        - black --version
        - --from=cogapp cog -v
        - urlscan --version
        - >
          --index-url=https://gitlab.com/api/v4/projects/43703506/packages/pypi/simple
          linkscan --version

- name:
    Tag vim help files, these tasks always report a change so they are run last
    in the playbook
  hosts: all
  tasks:
    - name: Create a temporary file for use as a script to generate help tags
      ansible.builtin.tempfile: { state: file, suffix: .vim }
      register: site_script
      changed_when: false
    - name: List optional packages
      ansible.builtin.find:
        paths: ~/.vim/pack/submodules/opt/
        file_type: directory
      register: site_find
    - name: Write the commands to the script to avoid an error about too many
        command line flags
      ansible.builtin.copy:
        dest: "{{ site_script.path }}"
        content: |
          {% for i in site_find.files %}
          packadd {{ i.path | basename }}
          {% endfor %}
          helptags ALL
          quit
        mode: "0o700"
      changed_when: false
    - name: Generate help tags with vim and the script( {{ site_script.path }} )
      ansible.builtin.command: vim -S {{ site_script.path }}
      changed_when: true
    - name: Remove the temporary file used as script for generating help tags
      ansible.builtin.file:
        path: "{{ site_script.path }}"
        state: absent
      changed_when: false
