# site.yaml
# Copyright 2021 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
#
# Run as:
#
#     ansible-playbook -i::1, -c local site.yaml
#
# This playbook can be run as a normal user, no super-user privileges are
# necessary.
- name: Create the backupdir
  hosts: all
  tasks:
    - name: Make sure ~/.backupdir exists
      ansible.builtin.file:
        state: directory
        path: ~/.backupdir
        mode: "0o700"

- name: Ensure that uv is installed
  hosts: all
  vars:
    site_uv_url: |-
      https://github.com/astral-sh/uv/releases/download/0.4.16/uv-x86_64-unknown-linux-gnu.tar.gz
    site_uv_checksum: |-
      f4f4de434206fb610ecb2dbc3fc44c62adb6b61e8d1237d858a10b407a2737c4
  tasks:
    - name: Try running uv version
      ansible.builtin.command: uv version
      failed_when: false
      changed_when: false
      register: site_uv_version_command
    - name: Stop this play if version command succeeded
      ansible.builtin.meta: end_host
      when: site_uv_version_command.rc == 0
    - name: Make sure ~/.local/bin exists
      ansible.builtin.file:
        state: directory
        path: ~/.local/bin
        mode: "0o755"
    - name: Create temporary download directory
      ansible.builtin.tempfile:
        state: directory
        suffix: -uv
      register: site_download
    - name: Download uv .tar.gz
      ansible.builtin.get_url:
        dest: "{{ site_download.path }}"
        url: "{{ site_uv_url }}"
        checksum: "sha256:{{ site_uv_checksum }}"
        mode: "0600"
    - name: Extract
      ansible.builtin.unarchive:
        src: "{{ site_download.path }}/uv-x86_64-unknown-linux-gnu.tar.gz"
        dest: "{{ site_download.path }}"
        remote_src: true
    - name: Install binaries
      ansible.builtin.copy:
        src: "{{ site_download.path }}/uv-x86_64-unknown-linux-gnu/{{ item }}"
        dest: ~/.local/bin/
        mode: "0o755"
      loop: [uv, uvx]

- name: Download scripts to the plugin/ directory
  hosts: all
  tasks:
    - name: Create the plugin folder
      ansible.builtin.file: { state: directory, path: ./plugin/, mode: "0o755" }
    - name: Download osc52.vim
      ansible.builtin.get_url:
        dest: ./plugin/osc52.vim
        url: |-
          https://raw.githubusercontent.com/libapps/libapps-mirror/main/hterm/etc/osc52.vim
        mode: "0640"
    - name: Download fzf.vim
      ansible.builtin.get_url:
        dest: ./plugin/fzf.vim
        url: |-
          https://raw.githubusercontent.com/junegunn/fzf/master/plugin/fzf.vim
        mode: "0640"
      # On Alpine Linux the fzf-vim package also includes documentation so
      # prefer to install that package manually
      when: ansible_distribution not in ('Alpine')

- name: Make sure packages are available through npx
  hosts: all
  tasks:
    - name: Check if npm is available
      ansible.builtin.command: npm --version
      changed_when: false
      register: npm_check
    - name: Stop this play if npm isnt't available
      ansible.builtin.meta: end_host
      when: npm_check.rc != 0
    - name: Make sure tools are available in the npm cache
      ansible.builtin.command:
        cmd: npm exec --yes -- {{ item }} --help
        creates: ~/.npm/_npx/*/node_modules/.bin/{{ item }}
      loop:
        - embedme
        - pyright
        - lint-staged
    - name: Make sure markdown-toc is available in the npm cache
      ansible.builtin.command:
        cmd: npm exec --yes -- markdown-toc --help
        creates: ~/.npm/_npx/*/node_modules/.bin/markdown-toc
      register: npm_exec_markdown_toc_cmd
      failed_when: npm_exec_markdown_toc_cmd.rc not in (0, 1) # 0 if skipped
    - name: Make sure ~/.local/bin exists
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: "0o755"
      loop: [~/.local, ~/.local/bin]
    - name: Install ~/.local/bin/prettier
      ansible.builtin.copy:
        dest: ~/.local/bin/prettier
        mode: "0o755"
        content: |
          #!/bin/sh
          exec npm exec --offline -- prettier "$@"
      when: "'.local/bin' in lookup('env', 'PATH')"
    - name: Add prettier to npm cache
      ansible.builtin.command: npm exec --yes -- prettier --version
      when: "'.local/bin' in lookup('env', 'PATH')"
      changed_when: false
    - name: Install ~/.local/bin/jsonlint
      ansible.builtin.copy:
        dest: ~/.local/bin/jsonlint
        mode: "0o755"
        content: |
          #!/bin/sh
          exec npm exec --offline -- jsonlint "$@"
      when: "'.local/bin' in lookup('env', 'PATH')"
    - name: Add jsonlint to npm cache
      ansible.builtin.command: npm exec --yes -- jsonlint --version
      when: "'.local/bin' in lookup('env', 'PATH')"
      changed_when: false
      register: npm_exec_jsonlint_cmd
      failed_when: npm_exec_jsonlint_cmd.rc != 1
    - name: Install ~/.local/bin/pyright-langserver
      ansible.builtin.copy:
        dest: ~/.local/bin/pyright-langserver
        mode: "0o755"
        content: |
          #!/bin/sh
          exec npm exec --package pyright --yes -- pyright-langserver "$@"
      when: "'.local/bin' in lookup('env', 'PATH')"
    - name: Add reuse to the cache so that tests can pass offline
      ansible.builtin.command: uv tool run reuse --help
      changed_when: false

- name:
    Tag vim help files, these tasks always report a change so they are run last
    in the playbook
  hosts: all
  tasks:
    - name: Create a temporary file for use as a script to generate help tags
      ansible.builtin.tempfile: { state: file, suffix: .vim }
      register: site_script
      changed_when: false
    - name: List optional packages
      ansible.builtin.find:
        paths: ~/.vim/pack/submodules/opt/
        file_type: directory
      register: site_find
    - name: Write the commands to the script to avoid an error about too many
        command line flags
      ansible.builtin.copy:
        dest: "{{ site_script.path }}"
        content: |
          {% for i in site_find.files %}
          packadd {{ i.path | basename }}
          {% endfor %}
          helptags ALL
          quit
        mode: "0o700"
      changed_when: false
    - name: Generate help tags with vim and the script( {{ site_script.path }} )
      ansible.builtin.command: vim -S {{ site_script.path }}
      changed_when: true
    - name: Remove the temporary file used as script for generating help tags
      ansible.builtin.file:
        path: "{{ site_script.path }}"
        state: absent
      changed_when: false
    - name: Ignore tag files that are not included in .gitignore
      ansible.builtin.lineinfile:
        line: doc/tags
        state: present
        path: ~/.vim/.git/modules/pack/submodules/opt/{{ item }}/info/exclude
      loop: [sexp, limelight]
