# site.yaml
# Copyright 2020 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
#
# Usage:
#
#     ansible-playbook -i, -u $USER site.yaml
#
- name: osc52.vim
  tags: always
  hosts: localhost
  become: yes
  vars:
    url: https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/osc52.vim
    dest: /usr/share/vim/vimfiles/plugin
  tasks:
    - name: Create the plugin folder
      file: { state: directory, path: "{{ dest }}", mode: 0o755 }
      when: ansible_distribution == 'Alpine'
    - name: Download osc52.vim
      get_url: { dest: "{{ dest }}", url: "{{ url }}" }
      when: ansible_distribution == 'Alpine'
# see also tasks/vim-help.yaml
# see also tasks/vim-links.yaml
