# site.yaml
# Copyright 2020 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
#
# Usage:
#
#     ansible-playbook -i, -u $USER site.yaml
#
- name: Install vim
  tags: always
  become: yes
  hosts: localhost
  tasks:
    - when: ansible_distribution == 'Ubuntu'
      name:
        Update to a recent vim on Ubuntu using a PPA, which is a prerequisite
        for tasks/matkaba.yaml
      block:
        - name: Install dependencies for apt Ansible module called via package
          package: { name: [python-apt, aptitude] }
        - name: Install dirmngr for apt_key
          package: { name: dirmngr }
        - name: Add apt key for Ubuntu ppas with recent vim
          apt_key:
            keyserver: "hkps://keyserver.ubuntu.com:443"
            id: 4ab0f789cba31744cc7da76a8cf63ad3f06fc659
        - name: Install Ubuntu ppas for a recent vim
          apt_repository: { repo: "{{ item }}" }
          loop:
            - deb http://ppa.launchpad.net/jonathonf/vim/ubuntu {{
              ansible_distribution_release }} main
            - deb-src http://ppa.launchpad.net/jonathonf/vim/ubuntu {{
              ansible_distribution_release }} main
        - name: Install current vim on Ubuntu
          apt: { name: "vim=2:8.1*", update_cache: yes }
    - name: Add the vi link on Alpine Linux
      when: ansible_distribution == 'Alpine'
      file: { state: link, src: /usr/bin/vim, path: /usr/local/bin/vi }

- name: osc52.vim
  tags: always
  hosts: localhost
  become: yes
  vars:
    url: https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/osc52.vim
    dest: /usr/share/vim/vimfiles/plugin
  tasks:
    - name: Create the plugin folder
      file: { state: directory, path: "{{ dest }}", mode: 0o755 }
      when: ansible_distribution == 'Alpine'
    - name: Download osc52.vim
      get_url: { dest: "{{ dest }}", url: "{{ url }}" }
      when: ansible_distribution == 'Alpine'

- name: Dependencies for ./autoload/fzf.vim
  tags: always
  hosts: localhost
  tasks:
    - name:
        Enable stretch-backports repository following
        https://backports.debian.org/Instructions/
      become: yes
      apt_repository:
        repo: deb https://deb.debian.org/debian stretch-backports main
      when: ansible_distribution == 'Debian'
    - name: Install fzf on Debian GNU/Linux
      become: yes
      apt: { default_release: stretch-backports, name: fzf }
      when: ansible_distribution == 'Debian'
    - name: Install default settings
      become: yes
      copy:
        dest: /etc/profile.d/fzf.sh
        mode: 0o444
        content: |
          export FZF_DEFAULT_COMMAND='find . -type f'
          export FZF_DEFAULT_OPTS='--height 10'

- name: Other system packages to work with vim plugins
  tags: always
  hosts: localhost
  tasks:
    - name:
        Install sshfs because it works better with ALE linters than netrw and
        scp; need fuse to unmount directories with fusermount -u
      become: yes
      package: { name: [sshfs, fuse] }
    - name: jq for an ALE JSON fixer and for command line use
      become: yes
      package: { name: jq }
    - name: jedi for use with Python
      become: yes
      package: { name: py3-jedi@edge-community }
      when: ansible_distribution == 'Alpine'

- name:
    Setup vimrc, do this last as the vimrc assumes packages are available and if
    another step fails this may leave vim difficult to start
  tags: always
  hosts: localhost
  tasks:
    - name: Create a link from ~/.vim for ansible user
      file:
        follow: no
        src: "{{ playbook_dir }}"
        path: "/home/{{ ansible_user }}/.vim"
        state: link
        group: "{{ ansible_user }}"
        owner: "{{ ansible_user }}"
      when: ansible_connection == 'local'
    - name:
        Create a link from ~/.vim for root user; except on Fedora to avoid "src
        file does not exist"
      become: yes
      file:
        follow: no
        src: "{{ playbook_dir }}"
        path: /root/.vim
        state: link
        group: root
        owner: root
      when: ansible_distribution in ('Ubuntu', 'Debian', 'Alpine')
# see also tasks/vim-help.yaml
