#!/bin/sh
# tests/run
# Copyright 2020 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0

# If run as tests/run from the root of the repository
test -d automated || cd tests || exit

for i in automated/* ; do
  if [ -d "$i" ] ; then
    cd "$i" || exit 1
    if ! ./run ; then
      printf 'tests/%s failed\n' "$i"
      exit 1
    fi
    cd ../.. || exit 1
  elif [ -f "$i" ] ; then
    if ! vim '+packadd vader | Vader!' "$i" ; then
      printf 'tests/%s tests failed\n' "$i"
      exit 1
    fi
  else
    printf 'tests/%s not recognised\n' "$i"
    exit 1
  fi
done

git branch --show-current > .success
printf 'tests/run: All tests succeeded.\n'
