#!/bin/sh
# tests/automated/backlog/run
# Copyright 2025 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
# For debugging use `:Vader` instead of `:Vader!`
../../../pack/vendored/start/backlog/tests/run.vader
