#!/bin/sh
# hooks/pre-commit
# Copyright 2021 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
npm exec -- lint-staged \
&& if git symbolic-ref -q HEAD | grep -q master ; then
  printf 'Avoid committing to master directly\n' \
  && exit 1
fi
# For some reason in certain environments tests/run.sh takes over a minute to
# execute if run as a pre-commit hook. A typical execution is less than ten
# seconds.
