#!/bin/sh
# tests/automated/embedme/run
# Copyright 2021 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
cp missing.md example.md \
&& vim \
  "+edit example.md" \
  '+normal \aq' \
&& git diff --exit-code example.md
