#!/bin/sh
# .hooks/pre-commit
# Copyright 2021 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
npm exec --prefer-offline -- lint-staged \
&& if git symbolic-ref -q HEAD | grep -q main ; then
  printf 'Avoid committing to the main branch directly\n' \
  && exit 1
fi
# For some reason in certain environments tests/run takes over a minute to
# execute if run as a pre-commit hook. A typical execution is less than ten
# seconds.
