#!/usr/bin/python3
"""pre-merge-commit hooks for vimfiles."""
# .hooks/pre-merge-commit
# Copyright 2021 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
from os import execvp
from pathlib import Path
from shutil import which
from subprocess import check_output
from time import time

COMMAND = ("git", "config", "core.hooksPath")

LIMIT = 1  # hour(s)


def _main() -> int:
    directory = Path(check_output(COMMAND).decode("utf8").strip())

    marker = directory / ".." / "tests" / ".success"
    try:
        age = (time() - marker.stat().st_mtime) / 60 / 60
    except FileNotFoundError:
        age = LIMIT + 1

    if age >= LIMIT:
        print("tests/.success is not found or is older than one hour")
        return 1

    if marker.read_text().strip() == "main":
        print("tests/.success contains 'main', run tests against a branch")
        return 1

    # don't run the pre-commit hook, as it prevents committing to main
    # instead run a script that is installed via
    # <https://github.com/maxwell-k/dotfiles/>, specifically
    # <https://github.com/maxwell-k/dotfiles/blob/main/dotfiles/local/bin/lint-all>
    executable = which("lint-all")
    if executable:
        execvp(executable, (executable,))  # noqa: S606
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
