#!/bin/sh
# tests/automated/spellcheck/run
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
# For debugging use `:Vader` instead of `:Vader!`
./spellcheck.vader \
&& echo "Text with no spelling mistakes." \
| vim '+call spellcheck#Exit()' -
